spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: skillbox
  jpa:
    hibernate:
      ddl-auto: update

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

