spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: skillbox
  jpa:
    hibernate:
      ddl-auto: update
  format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
    time: HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +375 29 7089887
  email: abdiev.dn@yandex.by
  copyright: Дмитрий Абдиев
  copyrightFrom: 2022

